### PR TITLE
Added "Docker Compose JUnit Rule Spark demo" as usecase

### PR DESCRIPTION
**Pull request by SchulteMarkus**
I really like this project Docker Compose JUnit Rule and I think, it really fills a gap. In my project, I had to combine it with some other tools for having continuous-integration testing. So I wrote "Docker Compose JUnit Rule Spark demo", which demonstrates my solution and might help other developers.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/docker-compose-rule](https://github.com/palantir/docker-compose-rule), @SchulteMarkus! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by SchulteMarkus** [comment]
@palantirtech I signed the license a while ago, any news?

**Comment by dotCipher** [comment]
Interesting, thanks for the contribution!

I think what might be a bit more reusable is pulling out the DCR related bits and omitting the Spark specific stuff.  Looking through your documentation I don't see any concrete examples of usage for DCR, but rather references to using it.

I would be open to adding an external references block in the README though, where we can reference this.

Question, is your current documentation still up-to-date based on it's usage?

**Comment by SchulteMarkus** [comment]
Closed as PR starved.

**Pull request closed without merging**
