### PR TITLE
Remove custom Gradle IDEA JDK logic

### LINKED ISSUE #66: Gradle Idea task assumes specific IDEA JDK naming scheme
Currently, this project's Gradle IDEA task assumes as specific naming scheme for the IntelliJ JDK/JRE -- specifically, "JavaSE-$version".

However, this isn't really standard, and makes it so that the out-of-the-box configuration doesn't work in many environments. Is there a reason that this is enforced? Omitting this custom logic should cause IntelliJ to just pick the correct JDK according to the version specified (verified locally and it seems to work)

### PR DESCRIPTION
**Pull request by nmiyake**
Fixes #66.

### CODE REVIEW

**Comment by nmiyake** [comment]
Previously, task generated following IDEA IML:

```
<component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8" inherit-compiler-output="true">
...
<orderEntry type="jdk" jdkName="JavaSE-1.8" jdkType="JavaSDK" />
```

With this PR, it generates the following:

```
<component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8" inherit-compiler-output="true">
<orderEntry type="jdk" jdkName="1.8" jdkType="JavaSDK" />
```

Basically, desire is to allow the JDK name to be handled by the plugin rather than specified. Unless there's a reason that an entire workspace has to specifically use the "JavaSE-" naming scheme, don't think it should be assumed.

**Comment by CRogers** [comment]
Hmm, odd that piece of code is in there. I don't have the JavaSE naming either.

**Comment by CRogers** [comment]
You need to merge in master to make this branch mergable.

**Comment by felixdesouza** [comment]
+1 for this.

**Comment by nmiyake** [comment]
Merged in master

**Comment by joelea** [comment]
Thanks @nmiyake !

**Pull request merged**
