### PR TITLE
Extra Health Checks (with first being JDBCContainerHealthCheck)

### PR DESCRIPTION
**Pull request by dotCipher**
## Highlights
- Added gradle submodule for extra health-checks
- Added `JdbcContainerHealthCheck` for handling appropriate database readiness signal
   - Includes convenience constructors for `postges` and `mysql`, but more could be added fairly trivially.
   - Will fail fast on `JdbcContainerConfiguration` construction, based on using the `DriverManager` API.  It will interpret if the configured JDBC Url can be handled by any of the current `Driver`s loaded in the runtime, before a docker `Container` is ever started.  This saves time from having to wait for the default to `ClusterWait` to timeout.

## RFC
@iamdanfox

### CODE REVIEW

**Comment by dotCipher** [comment]
@iamdanfox I might be missing something but is circle being finicky here?

**Comment by yiweig** [comment]
+1 on getting this feature in

**Comment by euclio** [comment]
+1, just ran into a flaky test due to this issue.

**Comment by dotCipher** [comment]
Not sure if we should encourage users to use the solution posted by `mdotson` on #202 
(example:
```
healthcheck:
  test: ["CMD", "psql", "-h", "localhost", "-c", "SELECT version();"]
  interval: 1s
  timeout: 5s
  retries: 12
```
)

Or we go with this codified option.  @iamdanfox, any thoughts?

**Comment by kasecato** [comment]
@dotCipher @dotson I don't think docker `healthcheck` and `jdbc` are the same. I tried it both, but your PR jar succeeded in testing and docker healthcheck fails in my test.

**Comment by dotCipher** [comment]
Interesting note @kasecato , that might mean that we should try and get this merged.  Apologies on the original radio silence

**Comment by dotCipher** [comment]
@iamdanfox would you be able to take a look at the errors on circle here?  It seems like the version of docker engine that circle is running isn't what compose expects?

Would we be able to get this merged?

**Comment by chrisalice** [comment]
As mentioned on slack, the build error is because public CircleCI doesn't support docker-compose files at version 3.1.

**Comment by chrisalice** [comment]
I strongly recommend trying to get a more representative docker healthcheck coded, rather than merging this, as then you'll not only get docker-compose-rule working, but any other healthcheck-using systems can use the result (e.g. docker ps!)

**Comment by dotCipher** [comment]
@alicederyn I am still a bit confused as to what you mean by "more representative docker healthcheck"?  Can you elaborate a bit more?

**Comment by alicederyn** [comment]
Kasecato wrote "I don't think docker healthcheck and jdbc are the same" -- but the Docker healthcheck is an arbitrary script so it can be anything we want. We just need to write one that better matches jdbc.

**Comment by dotCipher** [comment]
Closing due to staleness

**Pull request closed without merging**
