### PR TITLE
Implement start/stop/state for containers.

### PR DESCRIPTION
**Pull request by jkozlowski**
@joelea

### CODE REVIEW

**Comment by joelea** [comment]
LGTM - @felixdesouza / @iamdanfox you guys seems to be handling this stuff so I'll let you worry about merge/release.

**Comment by jkozlowski** [comment]
@felixdesouza @iamdanfox, any chance of merging?

**Comment by iamdanfox** [comment]
I don't think I quite understood the use case for this feature, but the code all looks fine!

**Comment by jkozlowski** [comment]
The usecase is to be able to start/stop container mid-test to test some failure scenarios.

**Pull request merged**
