### PR TITLE
Docker compose up individual containers

### PR DESCRIPTION
**Pull request by d-lorenc**
Add up method on container level to allow starting individual containers

Signed-off-by: Dariusz Lorenc <dlorenc@pivotal.io>

### CODE REVIEW

**Comment by hpryce** [comment]
@d-lorenc - sorry to not comment on this earlier, but we actually built similar functionally shortly before you submitted this. Is it possible to take a look at the new start/stop methods in DockerCompose and see if they'll let you do what you want?

If you would like to go ahead with a contribution, is it possible for you to review our contributing document at https://github.com/palantir/docker-compose-rule/blob/master/CONTRIBUTING.md
Sorry that this wasn't available when you first made this PR, but hopefully the latest version will be good for you anyway.

**Comment by d-lorenc** [comment]
We have already seen the start and stop methods. We were actually using them already, and  we based the implementation of the up method on them. 

In our (test) scenarios we need the start/stop, but we also would benefit from the up for the individual container too. We are testing relatively complex distributed system in different failover scenarios and the up method is handy especially when we want to start a smaller subset of components, or have them started in a particular order etc.

I have emailed my CLA.

**Comment by iamdanfox** [comment]
This looks fine to merge - I'm going to close and re-open to trigger the new CLA bot...

**Comment by iamdanfox** [comment]
@d-lorenc could you merge `master` into this branch and we'll get this merged.  Do you want a release cut?

**Comment by d-lorenc** [comment]
@iamdanfox the branch has been updated. Could you please merge? If could also cut a release, that would be great. Thanks.

**Pull request merged**
